version: '3'

services:
  db:
    image: postgres:11.2
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
  web:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata: